### PR TITLE
Task 2 React Components

### PR DESCRIPTION
**Pull request by Laranto-spb**
Maybe I went ahead with Components (structure).
I mixed up Material-UI and Materialize CSS (( Should I move to Material UI?

### CODE REVIEW

**Comment by ArtsiomLysianok** [comment]
> Maybe I went ahead with Components (structure). I mixed up Material-UI and Materialize CSS (( Should I move to Material UI?

**Comment by Artsiom-L** [comment]
> > Maybe I went ahead with Components (structure). I mixed up Material-UI and Materialize CSS (( Should I move to Material UI?

Yes, don't mix that.

**Comment by Artsiom-L** [comment]
> Maybe I went ahead with Components (structure). I mixed up Material-UI and Materialize CSS (( Should I move to Material UI?

In the task pointed that all code should be placed in one component.

**Comment by Laranto-spb** [comment]
Installed Material UI, one component with 3 cards ant heading, removed Materialize-CSS

**Review by Artsiom-L — APPROVED** [review]

**Pull request merged**
